function testRebaseWithError() {
    console.log('Error1');
}