function testRebaseWithError() {
    console.log('Error');
}